name: Build runner image

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
                
      - name: Authenticate with the Github Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin
      
      - name: Get the tag
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: docker push ghcr.io/asianjohnboi/build-runner:${{ steps.vars.outputs.tag || latest }}
